---
driver:
  name: vagrant
  network:
  - ["private_network", { ip: "192.168.33.118" }]

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[owasp-skf::default]
    attributes:
